# Generated by Django 3.1.3 on 2021-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_auto_20210507_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Click Above link to read blog post', max_length=250),
        ),
    ]
